services:
  pms:
    image: ${PMS_REGISTRY:? PMS_REGISTRY env variable missing}/pms:${PMS_APP_TAG:? PMS_APP_TAG env variable missing}
    container_name: pms
    env_file:
      - .env.pms
    restart: always
    # ports:
    #   - 127.0.0.1:${HOST_PORT:8000}:8000

networks:
  default:
    name: llm-scheduler
    external: true
