services:
  pms:
    image: ${PMS_REGISTRY:? PMS_REGISTRY env variable missing}/pms:${PMS_APP_TAG:? PMS_APP_TAG env variable missing}
    container_name: pms
    env_file:
      - .env.pms
    restart: always
    ports:
      - "${PMS_BIND_URL-127.0.0.1}:${PMS_BIND_PORT-8060}:8000"

networks:
  default:
    name: llm-scheduler
    external: true
